# Generated by Django 5.0 on 2023-12-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentModel',
            new_name='Instrument_Model',
        ),
    ]
