# Generated by Django 5.0 on 2023-12-06 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician_app', '0002_rename_instrumentmodel_instrument_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=0, max_digits=5)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician_app.musician_model')),
            ],
        ),
    ]
