# Generated by Django 5.0 on 2023-12-07 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0002_alter_album_model_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='album_model',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_app.starratingmodel'),
        ),
    ]
