# Generated by Django 5.0 on 2023-12-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0003_starratingmodel_alter_album_model_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starratingmodel',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
